var ActionConstants = {
  ACTION_NAVIGATE: "NAVIGATE",
  ACTION_LOGIN: "LOGIN",
  ACTION_REGISTER_USER: "REGISTER",
  ACTION_GETRESUME: "GETRESUME",
  ACTION_RESUMERECEIVED: "RESUMERECEIVED",
  ACTION_REGISTER_USER_COMPLETE: "REGISTERUSERCOMPLETE"
}

module.exports = ActionConstants;